### PR TITLE
Support --os-auth-type / OS_AUTH_TYPE

### PR DESCRIPTION
**Pull request by jobrs**
support the OpenStack standard --os-auth-type / OS_AUTH_TYPE parameter, so that conflicting settings for password and token can be resolved. 

Previously you could _either_ set token or password and (qualified) username / user-id but never both because there is no defined precedence.

### CODE REVIEW

**Comment by jobrs** [comment]
@notque what is missing is a unit test in pkg/cmd/cmd_test.go

**Comment by kayrus** [comment]
You can also add application credentials support: https://github.com/gophercloud/gophercloud/pull/1224

**Comment by jobrs** [comment]
@kayrus let's do this, but in a separate PR.

**Comment by jobrs** [comment]
@notque @chuan137 looks good now. So if you feel comfortable, too, we can merge this, add a new release 1.0.4 and integrate

**Pull request merged**
